--FUNCIÓN REPASO CLASE
-- Primero declaramos las variables
DECLARE @CONT INT, @MAX INT
DECLARE @NOMBRE NVARCHAR(25)
DECLARE @ISVIP BIT 

SELECT @CONT = MIN(CODIGO) FROM SOCIOS
SELECT @MAX = MAX(CODIGO) FROM SOCIOS


PRINT 'CÓDIGO SOCIO    -    NOMBRE SOCIO    -    CLIENTE VIP'
WHILE (@CONT <= @MAX)
    BEGIN
        IF(EXISTS(SELECT * FROM SOCIOS WHERE CODIGO = @CONT))
            BEGIN
                SELECT @NOMBRE = NOMBRE, @ISVIP = CLIENTEVIP FROM SOCIOS WHERE CODIGO = @CONT
                SET @NOMBREPELI = MINCALIFICAC(@CONT,'VHS')
                    IF (@ISVIP = 1)
                        BEGIN
                            PRINT CAST(@CONT AS NVARCHAR(6)) + SPACE(9) + @NOMBRE + SPACE(9) + 'SI'
                        END
                    ELSE
                        BEGIN
                            PRINT CAST(@CONT AS NVARCHAR(6)) + SPACE(9) + @NOMBRE + SPACE(9) + 'NO'
                        END
                PRINT CAST(@CONT AS NVARCHAR(6)) + SPACE(7) + @NOMBRE
            END
        SET @CONT +=1
    END

--PRIMERO VER COMO ESTAN ORGANIZADAS LAS TABLAS ALQUILER, PELICULAS Y STOCK
--OBTENER LA PELICULA CON MENOS CALIFICACIÓN POR CADA SOCIO

DECLARE @NOMPELICULA NVARCHAR(30), @CALIFICA INT

CREATE FUNCTION MINCALIFICA (@CODIGOSOCIO INT, @CODIGOSTOCK INT)
RETURN  NVARCHAR(40)
AS
BEGIN
    DECLARE @NOMPELICULA NVARCHAR(40), @CALIFICA INT
    SELECT TOP 1 @CALIFICA=CALIFICACION,@NOMPELICULA=P.TITULO 
    FROM ALQUILER A INNER JOIN STOCK ST ON ST.CODIGO=A.CODIGO_STOCK 
                    INNER JOIN PELICULAS P ON P.CODIGO=ST.CODIGO_PELICULA
    WHERE CODIGO_SOCIO=@CODIGOSOCIO AND FORMATO=@CODIGOSTOCK
    ORDER BY CALIFICACION ASC
    RETURN @NOMPELICULA
END



