--ACTUALIZAR STOCK

/*Actualizar las unidades de existencia de los productos asignándoles el
valor de 1000 de aquellos productos cuyo stock sea cero.*/
USE NEGOCIOS2011
GO

DECLARE @ID INT, @NOMBRE VARCHAR(50)

WHILE EXISTS (SELECT *
			FROM TB_PRODUCTOS
			WHERE UNIDADESENEXISTENCIA=0)
	BEGIN
			SELECT TOP 1 @ID= P.IDPRODUCTO, @NOMBRE=P.NOMBREPRODUCTO
			FROM TB_PRODUCTOS P
			WHERE UNIDADESENEXISTENCIA=0

			UPDATE TB_PRODUCTOS
			SET UNIDADESENEXISTENCIA=1000
			WHERE IDPRODUCTO=@ID

		PRINT 'PRODUCTO:'+@NOMBRE + ' SE ACTUALIZO EL STOCK'

		CONTINUE
	END;	